### ISSUE TITLE
How to use it without Qml

### ISSUE THREAD

**Issue by yangpenglove** [moritzstoetter/qt6purchasing#1]
Hello, thanks for your sharing.

Our product is old and cannot use qml,  can you kindly show some c++ sample code for testing?

Thanks

**Comment by moritzstoetter** [comment]
Hi, thank you for your interest in this library. 

Unfortunately I don't have any sample code that uses this library without QML. Also I suspect that some tweaking will be necessary to use this in pure Qt6/C++. Should be pretty straight forward though. Happy coding!
