### ISSUE TITLE
QML error

### ISSUE THREAD

**Issue by MohammadKanan** [moritzstoetter/qt6purchasing#8]
When I follow QML creation instructions, I get this error when opening the page that contains `Store{}`
` qrc:/Src/QML/Subscription/SubscribtionsMain.qml:324:13: Type TheStore unavailable
W Gravi   : qrc:/Src/QML/Subscription/TheStore.qml:7:3: Cannot assign object to list property "productsQml"`

**Comment by moritzstoetter** [comment]
Hi Mohammad, 

thanks for taking such an interest in this repo. Unfortunately I must tell you that I won't be much help with any issues. I haven't touched the repo in over two years now, or Qt for that matter. I am not using it anymore myself and I don't know how Qt and the purchasing thing in it has evolved in that time. 

So please regard this as a starting point for your own journey, more than a ready made solution. I hope this can still be useful to you.

Best of luckl
